x-envvars: &ci_environment
  environment:
    DJANGO_SETTINGS_MODULE: hub20.api.settings
    HUB20_DATA_FOLDER: /var/hub20
    HUB20_STATIC_ROOT: /var/hub20/static
    HUB20_CORS_HEADERS_ENABLED: 1
    HUB20_DATABASE_HOST: db
    HUB20_DATABASE_PORT: 5432
    HUB20_DATABASE_NAME: hub20
    HUB20_DATABASE_USER: hub20
    HUB20_DATABASE_PASSWORD: hub20_pass
    HUB20_EMAIL_MAILER_ADDRESS: noreply@hub20.example.com
    HUB20_EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
    HUB20_SECRET_KEY: base-hub20-secret-key
    HUB20_WALLET_MODEL: ethereum.KeystoreAccount

services:
  db:
    <<: *ci_environment
    image: postgres

  redis:
    image: redis:latest

  web:
    <<: *ci_environment
    image: "hub20:${TAG:-latest}"
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        django-admin migrate;
        django-admin collectstatic --noinput
        uvicorn hub20.api.asgi:application --port 80 --host 0.0.0.0 --reload --reload-dir /app/hub20
      "
    build:
      context: ../../
    depends_on:
      - db
      - redis
